name: Build and Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  check-tag:
    name: Check build tag
    runs-on: ubuntu-latest
    outputs: 
        releaseExists: ${{ steps.check-tag.outputs.exists }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Client Project version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: API/PrimeNGTemplate.API/PrimeNGTemplate.API.csproj

      - uses: mukunku/tag-exists-action@v1.6.0
        id: check-tag
        with: 
          tag: 'v${{ steps.get-version.outputs.package-version }}'

  createRelease:
    name: Build and Create Release
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'false'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 23.6.0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile Web Client project as publish files
        run: |
            cd Frontend
            npm i --legacy-peer-deps
            npm run deploy primengtemplate
            cd ..
            cd ..

      - name: Compile API project as publish files
        run: dotnet publish .\API\PrimeNGTemplate.API\PrimeNGTemplate.API.csproj /p:PublishProfile="PackagePublish.pubxml"

      - name: Compile Database project as publish files
        run: msbuild .\Database\PrimeNGTemplate.Database\ /p:OutputPath=../../Output/Database /P:Configuration=Release

      - name: Compress Web Client build files
        uses: vimtor/action-zip@v1.2
        with:
          files: Output/Frontend/browser/
          dest: Output/web client.zip

      - name: Compress API build files
        uses: vimtor/action-zip@v1.2
        with:
          files: Output/API/net10.0/publish/
          dest: Output/api.zip

      - name: Compress Database build files
        uses: vimtor/action-zip@v1.2
        with:
          files: Output/Database/
          dest: Output/database.zip

      - name: Get API Project version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: .\API\PrimeNGTemplate.API\PrimeNGTemplate.API.csproj
          
      - name: Create Tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: "v${{ steps.get-version.outputs.package-version }}"
      
      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          artifacts: "Output/*.zip"
          tag: "v${{ steps.get-version.outputs.package-version }}"
          generateReleaseNotes: true

  testBuild-windows:
    name: Build and Test (windows)
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'true'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        
      - name: Build Database
        run: msbuild .\Database\PrimeNGTemplate.Database\

  testBuild-linux:
    name: Build and Test (linux)
    needs: check-tag
    if: needs.check-tag.outputs.releaseExists == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 23.6.0

      - name: Build API
        run: dotnet build ./API/PrimeNGTemplate.API/PrimeNGTemplate.API.csproj
        
      - name: Build Web Client
        run: |
            cd Frontend
            npm i --legacy-peer-deps
            npm run build
